### PR TITLE
include openssl include dir (necessary when it is not standard)

### PR DESCRIPTION
**Pull request by fabrice102**
When OpenSSL is not installed in a standard place, it is necessary to include its include dir.

### CODE REVIEW

**Comment by wangxiao1254** [comment]
I proposed to add openssl dir in
https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool-config.cmake#L11
It will become
set(EMP-TOOL_INCLUDE_DIRS ${EMP-TOOL_INCLUDE_DIR}/include/emp-tool/ ${OPENSSL_INCLUDE_DIR})
In this way, we don't need to change other projects.

What do you think?

**Comment by fabrice102** [comment]
Thanks. This is indeed a simpler solution.

**Comment by wangxiao1254** [comment]
I didn't try it since my openssl is in the standard path. Can you try it and let me know? Then I can close this pull request and update the install files in emp-tool.

Thanks!

**Comment by fabrice102** [comment]
I've tried it. This is working for me. I can do a pull request if you want.

**Comment by wangxiao1254** [comment]
That will be wonderful! Thanks. I'm closing this pull request and ones in other repos.

**Pull request closed without merging**
