### PR TITLE
Workaround for a bug of clang with injected-class-name

### PR DESCRIPTION
**Pull request by fabrice102**
See https://stackoverflow.com/a/17687568

### CODE REVIEW

**Comment by wangxiao1254** [comment]
Maybe I should add a osx test in travis so that compatibility of clang will be check for all commits? @fabrice102 how hard is it to install all dependencies in osx?

**Comment by fabrice102** [comment]
I've never used Travis. But using Homebrew (https://docs.travis-ci.com/user/reference/osx/#Homebrew), dependencies were easy to install on my own computer. If I remember correctly the commands are

```
brew install gmp openssl
export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
```

The second command is necessary for `cmake` to find the `openssl` libraries (macOS only provides an outdated `openssl` library without headers; to avoid conflicts, Homebrew does not link `openssl` in `/usr/local`).

Don't hesitate to ask me if you have any further question.

**Comment by wangxiao1254** [comment]
Travis test environment in OSX does not support AESNI so I cannot test it on OSX. However, I tried to test it with clang 5.0 on Linux. The code without fix works fine.

https://travis-ci.org/emp-toolkit/emp-ot/jobs/255926035

**Comment by fabrice102** [comment]
My clang version is

```
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It seems that Apple is using a customized version of clang.

**Comment by wangxiao1254** [comment]
Ok I guess I will just test on OSX's clang locally. Feel free to submit pull requests if I miss anything :)

**Comment by fabrice102** [comment]
I may have missed something, but I have the impression that you are not using clang in https://travis-ci.org/emp-toolkit/emp-ot/jobs/255926035.

On your travis job, `cmake` outputs:

```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
```

while on my mac it outputs:

```
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
```

I'm not sure where the env variable `MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"` is used.

**Comment by wangxiao1254** [comment]
oops forget to     - eval "${MATRIX_EVAL}"!

**Comment by wangxiao1254** [comment]
Seems that clang 5.0 works... https://travis-ci.org/emp-toolkit/emp-ot/jobs/255931953#L1693

**Comment by fabrice102** [comment]
Apparently Apple LLVM 8.1.0 is based on LLVM 3.9.0:
https://gist.github.com/epipping/ef8b02b0cfaec4a5ebf3a57092145a3f

What happens if you try with clang-3.9?

**Comment by wangxiao1254** [comment]
ok good. now I can reproduce the same error! I will add clang 3.9 to all repos.

**Pull request merged**
