### PR TITLE
Use Boost aligned_alloc instead of C11 aligned_alloc

### PR DESCRIPTION
**Pull request by fabrice102**
For compatibility with macOS: macOS does not have C11 `aligned_alloc`

### CODE REVIEW

**Comment by fabrice102** [comment]
This required emp-toolkit/emp-tool#41 to compile (as it uses Boost and Boost libraries were not included before).

**Comment by wangxiao1254** [comment]
Just wanted to confirm: is it true that we also need to use `aligned_free` for those poitners allocated via `aligned_alloc`?

**Comment by fabrice102** [comment]
Indeed, I did not see that. It seems that the STD `aligned_malloc` is freed using `free`, but the `boost` one is freed using `aligned_free`.
@weikengchen's also required to use an `aligned_free` function.
It seems to be hard to avoid if we are not using STD...

So the above patch might yield memory leaks (or worse). It needs to be changed to use `aligned_free`.

**Comment by wangxiao1254** [comment]
I updated the code by manually incorporating the change and also update `aligned_free`

**Pull request closed without merging**
