### PR TITLE
Oblivious Transfer from Learning with Errors

### PR DESCRIPTION
**Pull request by mattsoulanille**
This pull request implements Oblivious Transfer based on the (presumed) hard problem Learning with Errors. The specific scheme that was implemented is due to [Peikert, Vaikuntanathan, and Waters](https://eprint.iacr.org/2007/348). More details on the scheme can be found in the design document.

#### New Files:
* [emp-ot/lattice.h](https://github.com/dvanclev/emp-ot/blob/no_timing_code/emp-ot/lattice.h) : Includes the implementation of the protocol and in-source documentation.
* [test/lattice.cpp](https://github.com/dvanclev/emp-ot/blob/no_timing_code/test/lattice.cpp) : Test code for the implementation.
* [install_packages_lattice.sh](https://github.com/dvanclev/emp-ot/blob/no_timing_code/install_packages_lattice.sh) : Shell script for installing the implementation's dependencies (eigen3 and boost random, timer, and system). Runs on macOS and ubuntu.
* [emp-ot/latticeInclude.h.in](https://github.com/dvanclev/emp-ot/blob/no_timing_code/emp-ot/latticeInclude.h.in) : "Compiled" by CMake into `latticeInclude.h` which defines `INCLUDE_LATTICE_OT` if and only if eigen is available, thus allowing the user to install emp-ot with or without support for our lattice package.
* [cmake/FindEigen3.cmake](https://github.com/dvanclev/emp-ot/blob/no_timing_code/cmake/FindEigen3.cmake) : Finds eigen when cmake is run if eigen is available.

#### Changes:
* [emp-ot/emp-ot.h](https://github.com/dvanclev/emp-ot/blob/no_timing_code/emp-ot/emp-ot.h) : Includes lattice.h if the dependencies are available (see CMakeLists.txt below).
* [CMakeLists.txt](https://github.com/dvanclev/emp-ot/blob/no_timing_code/CMakeLists.txt) : Edited to build lattice.cpp and include lattice.h in emp-ot/emp-ot.h if and only if the dependencies for lattice.h are installed (i.e. eigen is installed).
* [test/test.h](https://github.com/dvanclev/emp-ot/blob/no_timing_code/test/test.h) : Added a template for testing bit OT.
* [.gitignore](https://github.com/dvanclev/emp-ot/blob/no_timing_code/.gitignore) : Ignore cmake-generated emp-ot/latticeInclude.h.
* README.md : Add instruction for installing lattice dependencies.

### CODE REVIEW

**Comment by mattsoulanille** [comment]
Looks like CMake is asking for `boost-timer` and `boost_random` which are required by our lattice code. I'll modify CMakeLists to fix this issue.

**Comment by wangxiao1254** [comment]
It will great if users only need to add an extra flag in CMAKE to enable this module, without extra effort. For example, `CMAKE -DLATTICEOT=True .`

**Comment by mattsoulanille** [comment]
Oops. I committed this before reading your commend. The above commit checks if the dependencies for lattice are satisfied and builds lattice if and only if they are. I'll rewrite it so it takes a command line option as you described and complains if lattice dependencies aren't present.

**Comment by mattsoulanille** [comment]
This commit uses the `-DLATTICEOT=true` option instead of automatically including lattice OT if the dependencies are met.

**Comment by wangxiao1254** [comment]
I think you might forget to commit something. It seems that the current CMakeList file does not contain `LATTICEOT`. I tried `cmake -DLATTICEOT=true .` and it says:
`CMake Warning:  Manually-specified variables were not used by the project: LATTICEOT`

**Comment by mattsoulanille** [comment]
I've made sure to include the `CMakeLists.txt` file in this commit. Are you on the [no_timing_code](https://github.com/dvanclev/emp-ot/tree/no_timing_code) branch?

**Comment by wangxiao1254** [comment]
My bad, I was on a wrong branch :)

**Comment by wangxiao1254** [comment]
I cloned https://github.com/dvanclev/emp-ot/tree/no_timing_code and tested on a clean amazon EC2 machine. It installs eigen3 as shown here:
```
Unpacking pkg-config (0.29.1-0ubuntu1) ...
Selecting previously unselected package libeigen3-dev.
Preparing to unpack .../libeigen3-dev_3.3~beta1-2_all.deb ...
Unpacking libeigen3-dev (3.3~beta1-2) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up pkg-config (0.29.1-0ubuntu1) ...
Setting up libeigen3-dev (3.3~beta1-2) ...
```

For `cmake -DLATTICEOT=true .`, I got:
```
-- Building with support for lattice OT
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown



-- Configuring incomplete, errors occurred!
```

The version of ubuntu is 16.04

**Comment by mattsoulanille** [comment]
It seems that on 16.04, installing eigen3 from apt does not create the file `/usr/lib/cmake/eigen3/Eigen3ConfigVersion.cmake`, which is what lets CMake know what version of eigen3 is installed. This problem is not present on 18.04 or if eigen3 is installed from source.

I'll update the instructions and install script to install eigen3 from source. 

Another issue: If gcc is used to build anything that includes `lattice.h`, it must use the compile option `-fext-numeric-literals`. This probably won't matter in practice since no one will actually use `lattice.h` in implementations.

**Comment by mattsoulanille** [comment]
I believe this last commit (modifying `install_packages_lattice.sh`) should fix the issue with eigen3. All it does is build and install eigen3 from source instead of relying on the package manager.

**Comment by wangxiao1254** [comment]
Well done!

**Pull request merged**
